apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: jenkins
  labels:
    build_id: "__BUILD_ID__"  # Dynamically set by the pipeline to help in image hash verification
    image-hash-timestamp: "__IMAGE_HASH_TIMESTAMP__"  # Dynamically set by the pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        build_id: "__BUILD_ID__"  # Dynamically set by the pipeline
        image-hash-timestamp: "__IMAGE_HASH_TIMESTAMP__"  # Dynamically set by the pipeline
    spec:
      containers:
        - name: my-app-container
          image: __IMAGE_TAG__  # Dynamically set by the pipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsUser: 0
          env:
            - name: BUILD_ID
              value: "__BUILD_ID__"  # Dynamically set by the pipeline
            - name: IMAGE_HASH_TIMESTAMP
              value: "__IMAGE_HASH_TIMESTAMP__"  # Dynamically set by the pipeline
      imagePullSecrets:
        - name: aws-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: jenkins
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8082  # Exposing this port externally
      targetPort: 80  # The container's internal port (Nginx listens on port 80)
  type: LoadBalancer  # Ensures that the service is accessible externally (AWS ELB)
