apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: 533267172050.dkr.ecr.us-west-2.amazonaws.com/my-repo:__IMAGE_TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsUser: 1000
            fsGroup: 1000
  imagePullSecrets:
  - name: ecr-credentials
