apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-v3  # Deployment Resource
  namespace: jenkins
  labels:
    app: my-app-v3 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-v3
  template:
    metadata:
      labels:
        app: my-app-v3
        build_id: "__BUILD_ID__"  # dynamically replaced by the pipeline
    spec:
      serviceAccountName: jenkins-sa
      containers:
        - name: my-app-container
          image: "__IMAGE_TAG__"  # dynamically replaced by the pipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsUser: 1000  # root
          env:
            - name: BUILD_ID
              value: "__BUILD_ID__"  # This will be dynamically replaced by the pipeline
      imagePullSecrets:
        - name: aws-credentials  
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service3
  namespace: jenkins
spec:
  selector:
    app: my-app-v3  # Service Resource
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
  type: LoadBalancer
