apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-v3
  namespace: jenkins
  labels:
    app: my-app-v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-v3
  template:
    metadata:
      labels:
        app: my-app-v3
        build_id: "__BUILD_ID__"
    spec:
      containers:
        - name: my-app-container
          image: __IMAGE_TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsUser: 0
          env:
            - name: BUILD_ID
              value: "__BUILD_ID__"
      imagePullSecrets:
        - name: aws-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service3
  namespace: jenkins
spec:
  selector:
    app: my-app-v3
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
  type: LoadBalancer
