


AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for setting up Launch Template.'

Parameters:
  EnvironmentName:
    Type: String
    Default: 'Testing'
    AllowedValues:
      - Testing
      - Staging
      - Production
    Description: 'Environment name for resource tagging and identification.'

  NodeInstanceType:
    Type: String
    Default: t3.medium
    Description: 'EC2 instance type for the Kubernetes worker nodes.'

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: 'Name of an existing EC2 KeyPair to enable SSH access to the worker nodes.'

  EKSCluster:
    Type: String
    Description: 'Name of the EKS cluster.'
    
  Region:
    Type: String
    Default: us-west-2

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c94855ba95c71c99
    us-west-2:
      AMI: ami-0c60a682662b226b3
    eu-west-1:
      AMI: ami-0c94855ba95c71c99
    # Add more regions as needed

Resources:
  NodeGroupLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub '${EnvironmentName}-NodeGroupLaunchTemplate'
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 20
              VolumeType: gp2
        SecurityGroupIds: 
          - Fn::ImportValue: !Sub '${EnvironmentName}:EKSSecurityGroupId'
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "AMI"]
        InstanceType: !Ref NodeInstanceType
        KeyName: !Ref KeyPairName 
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -o xtrace
            /etc/eks/bootstrap.sh ${EKSCluster} --kubelet-extra-args '--node-labels=node.kubernetes.io/lifecycle=spot' --apiserver-endpoint https://${EKSCluster}.eks.${Region}.amazonaws.com --b64-cluster-ca $(aws ssm get-parameter --name /${EnvironmentName}/EKSClusterCA --region ${Region} --query 'Parameter.Value' --output text)
            echo "EKS_CLUSTER_CA=$(aws ssm get-parameter --name /${EnvironmentName}/EKSClusterCA --region ${Region} --query 'Parameter.Value' --output text)" >> /etc/eks/eks.conf
            echo "EKS_CLUSTER_ENDPOINT=https://${EKSCluster}.eks.${Region}.amazonaws.com" >> /etc/eks/eks.conf       

Outputs:
  LaunchTemplateId:
    Value: !Ref NodeGroupLaunchTemplate
    Export:
      Name: !Sub '${EnvironmentName}-LaunchTemplateId'
  LatestVersionNumber:
    Value: !GetAtt NodeGroupLaunchTemplate.LatestVersionNumber
    Export:
      Name: !Sub '${EnvironmentName}-LatestVersionNumber'
  LaunchTemplateName: 
    Value: !Ref NodeGroupLaunchTemplate
    Export:
      Name: !Sub '${EnvironmentName}-LaunchTemplateName'

