apiVersion: v1
kind: Service
metadata:
  name: my-app-service  # Name of the service
  namespace: jenkins  # Namespace where the service will be deployed
spec:
  selector:
    app: my-app  # This selector matches the labels defined in the deployment to select the Pods
  ports:
    - protocol: TCP
      port: 80  # The port that the service will expose
      targetPort: 80  # The port on the Pods that the service will forward traffic to
  type: LoadBalancer  # This exposes the service externally via a cloud provider's load balancer
