apiVersion: v1
kind: Secret
metadata:
  name: backend-sa-token
  namespace: jenkins
  annotations:
    kubernetes.io/service-account.name: backend-sa
type: kubernetes.io/service-account-token
