apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: stop-ebpf-monitor
  namespace: bcc-monitoring
spec:
  selector:
    matchLabels:
      name: ebpf-monitor-control-stop
  template:
    metadata:
      labels:
        name: ebpf-monitor-control-stop
    spec:
      containers:
      - name: ebpf-monitor-control-stop
        image: amazonlinux:2
        securityContext:
          privileged: true
        command: ["/bin/bash", "-c", "sudo chroot /host systemctl stop bcc"]
        volumeMounts:
        - name: host-root
          mountPath: /host
      volumes:
      - name: host-root
        hostPath:
          path: /
      restartPolicy: Always